### ISSUE TITLE
Cancelling the build takes too long

### ISSUE THREAD

**Issue by lucaswerkmeister** [ceylon/ceylon-ide-eclipse#1202]
If you cancel a Ceylon build, it can take quite some time until it actually stops.

**Comment by gavinking** [comment]
So I've fixed this as far as in-IDE typechecking goes. However I don't see a way to cancel the binary generation step when we hand off to the backend. @FroMage what do you think, is there a way we could provide cancellation for the binary generation step?

A second issue is that it seems that canceling the build is sorta useless, because, at least with Build Automatically enabled, a new build gets kicked off pretty soon after the cancelled build finishes.

**Comment by quintesse** [comment]
@gavinking what if you would put something like:

```java
if (monitor.isCanceled()) {
    throw new RuntimeException("XXXXXXXXXXXX");
}
```

in `started()` and `finished()` of the task listener around line 2611 of the `CeylonBuilder`?

If that does more or less what you want we could add an official `CompilationInteruptedException` instead and make sure that the compiler knows about it (exits with a proper exit code instead of BUG for example).

**Comment by gavinking** [comment]
@quintesse are you looking at this problem?

**Comment by quintesse** [comment]
Not in progress right now but I have it on my TODO list.

**Comment by gavinking** [comment]
OK, thanks.

**Comment by quintesse** [comment]
@davidfestal I don't think the idea was to close this yet ;)
But thanks for implementing the stop-gap solution for now.
But if you don't mind I'll re-open this so I know we have to come up with a better solution, ok?

**Comment by quintesse** [comment]
@davidfestal sorry, I see now that the discussion I had with @gavinking about this topic was not reflected here in this issue so you couldn't have known. Anyway, the idea was to create a proper solution in the compiler itself.

**Comment by FroMage** [comment]
I don't understand. This is already implemented by throwing, no? I don't think we can do better.

**Comment by quintesse** [comment]
@FroMage but isn't your progress stuff much more fine-grained? Meaning it would cancel much faster than what is possible now. At least as far as I know there are several phases in the compilation that have no task progress associated with them at all while your stuff seems to be everywhere :)
But if you think the current stuff is the best we can do you can close this if you want.

**Comment by davidfestal** [comment]
@quintesse ; I don't understand : do you really feel the cancelling of binary generation is long *now*?

**Comment by gavinking** [comment]
I agree with @quintesse.

**Comment by quintesse** [comment]
Ok, I must admit I'm currently unable to find a specific point where cancellation is slow (tried at several points during a build of the SDK and it never takes longer than a second). So maybe this has indeed improved sufficiently to close this issue.

**Comment by gavinking** [comment]
I suppose I agree. Cancelation _does_ work these days (except for #1517) even though I don't love the implementation, which I don't see us improving for 1.2.

Let's close it.
