### ISSUE TITLE
inheritance of Java interfaces not recognized by model loader

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1216]
I have, in a Ceylon module:

```java
public interface A { 
	public void foo();
} 
```

```java
public interface B extends A {
}
```

Now this Ceylon code does not typecheck:

```ceylon
void run(B b) {
    A a = b;
}
```

Because according to the model, `B` does not satisfy `A`.

@davidfestal would you take a look, please?

**Comment by davidfestal** [comment]
Seem to be fixed. Neither @gavinking nor me can reproduce it.

**Comment by gavinking** [comment]
Now, after a restart of Eclipse, the error came back.

**Comment by davidfestal** [comment]
Arg, even when restarting Eclipse, I don't get the error... I'll need more details from you in order to be able to reproduce the problem...

**Comment by gavinking** [comment]
oh oh oh.

To reproduce, add a module named `xxx.ceylon` to the project, where `xxx` is the name of the package with the Java code in it!

**Comment by gavinking** [comment]
Note, the java and ceylon code given above should be in a package in the _default module_!

**Comment by davidfestal** [comment]
In fact to reproduce it you just have to create a module name `xxx.something`, where `xxx` is the name of the package with the Java code in it.
It's because the `xxx.something` module, for an unexplained reason, contains the `xxx` package  inside its list of packages, which then misleads the modelLoader when trying to find out the super interfaces of B (since it finally searches B inside `xxx.something` module.  
Let me try to find out why.
