### ISSUE TITLE
Entry/exit breakpoints, preventing breakpoints

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-ide-eclipse#1243]
I'm sure this is planned, but since there's no issue for it...

In JDT/Debug if I try to set a breakpoint by double clicking in the margin/gutter on a line that's a method declaration I get a method entry breakpoint. In Ceylon/Debug I get a (useless) step breakpoint. Similarly in JDT if I try to set a breakpoint on a blank line (or other line that doesn't correspond to anything in the classfile's code attribute) then I'm prevented from setting any kind of breakpoint, but Ceylon/Debug will happily claim to set a breakpoint for me there anyway.

**Comment by davidfestal** [comment]
Also improved by the fix for #1281.
So the only pending point is allowing method entry / exit. However for this we should support method entry / exit breakpoints for Ceylon. For the moment it's not the case (mainly because we cannot always be sure of the fully qualified name of the method, as it will be in the generated Java code).

I think we should open a new issue for the support of Ceylon Method Entry Exit breakpoints.
@tombentley : wdyt ?

**Comment by tombentley** [comment]
Yeah, fine a new issue. Just had a go with the current debugging support and it's really pretty good. Thanks @davidfestal and @gavinking.

**Comment by davidfestal** [comment]
Happy to hear that! Thanks.
Do you want me to create the new issue ?

**Comment by tombentley** [comment]
Yes, please

**Comment by davidfestal** [comment]
done : #1285
