### ISSUE TITLE
debugging calls to functions with default parameters

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1260]
Given:

```ceylon
shared void bar() => foo();

shared void foo(Integer integer=1) 
        => print("goodbye");
```

When I debug this code, I stop in a stack frame with no line number information, between the body of `bar()` and the body of `foo()`. I assume this is the nullary `foo()` method that fills in the default argument values. Apparently it has no line number information.

Either:

1. it should be attributed the line number of the parameter list of the function, or
2. the debugger should skip it.

@davidfestal @tombentley  thoughts?

**Comment by davidfestal** [comment]
@tombentley : is it possible to assign the line number of the corresponding parameter of the function (in case they are on distinct line) ?

I propose to assign lines as follows, shown in the following generated code :
```Java
    public static void foo() {
        long $ceylontmp$integer$170 = foo$integer(); // associate with 
                                                     // the line of the
                                                     // 'integer' parameter
        // Do the same  for other default parameters if any
        foo($ceylontmp$integer$170); // associate with the first
                                     // line of the 'foo' Ceylon body
        Object var10000 = null;
    }
```

**Comment by davidfestal** [comment]
As soon as the line numbers are added, the `foo$integer()` call (and the similar calls in case of other default parameters) can be filtered if necessary.

**Comment by davidfestal** [comment]
@tombentley : any idea of what is doable in this regard ? Is there some place where I can look into to help ?

**Comment by tombentley** [comment]
I'll have a look

**Comment by davidfestal** [comment]
Thanks !

**Comment by tombentley** [comment]
I spent a while looking at this yesterday and it's going to be annoyingly hard to do. The reason is that we use the same infrastructure to generate the overload methods in contexts where we only have a model, but no `Tree` (for example mixin bridges), so the API is all in terms of model `ParameterList` and `Parameter` at the moment, and without the `Tree` nodes I can't generate line info. There are ways around that but it's not clear which is the least ugly of the possible hacks (ideally I want to make this code better not worse). I'll try out an idea today.

**Comment by tombentley** [comment]
@davidfestal I've pushed a `debug-lines` branch to `ceylon-compiler`. Can you please test that it's doing what you want? 

For `void` methods we still transform using a `Let`, so I had to attribute the `returning null` statement of the `Let`. I've attributed this to the method itself at the moment, but if that's not appropriate I can be able to do something else, but let me know.

**Comment by davidfestal** [comment]
@tombentley : OK, I'll check. Thanks

**Comment by davidfestal** [comment]
@tombentley : yes, it's far better. But now I realize that it would be better if the generated line :
```
        foo($ceylontmp$integer$170);
```
(that delegates to the real generated body), would be associated with the Ceylon line **just before** the first line of the Ceylon `foo()` method body. In fact, it would be the line of the last parenthesis of the method declaration.

It's because we still have one _step in_ to perform at this time in order to **really** be inside the `foo()` Ceylon body. So, for example, we don't see the default parameter variable in the Variables View. It's a bit disturbing IMO : we seem to have entered the Ceylon method body but haven't indeed.

**Comment by davidfestal** [comment]
@tombentley : Apart from this detail that is not critical, your push is OK for me.

**Comment by tombentley** [comment]
@davidfestalI've updated the branch, is that what you were after?

**Comment by davidfestal** [comment]
@tombentley : according to both the debugging experience and the result of _Javap_ on generated classes, it seems perfect for me.

Additionally, I pushed various commits that now allow to _enable / disable_ stepping into the default argument construction code : the `Filter and step through default argument code` Ceylon debugging option, that is `false` by default.

Now the following code : 

```Ceylon
Integer foofoo(Integer i)
        => i * 2;

shared void bar()
        => foo(1);

shared void foo(
    Integer fixedArg,
    Integer integer = foofoo(fixedArg),
    Integer additional = integer * 2
) 
        => print("goodbye");
```

So when stepping in from `bar()`, we stop at the following locations : 

- If `Filter and step through &default argument code` is `false` :
    - once in the body of `bar()`,
    - once on the line of the `integer` default argument definition with the `fixedArg` variable visible in the Variable View.
    - once in the body of `foofoo()` since the `integer` default argument construction code is filtered with step-through,
    - once on the line of the `additional` default argument definition with the `fixedArg` and `integer`variables visible in the Variable View.
    - once in the body of `foo()`, with the `fixedArg`, `integer` and `additional` variables visible in the Variable View.

- If `Filter and step through &default argument code` is `true` :
    - once in the body of `bar()`,
    - once in the body of `foofoo()` since the `integer` default argument construction code is filtered with step-through,
    - once in the body of `foo()`, with the `fixedArg`, `integer` and `additional` variables visible in the Variable View.

It seems very good to me.
@gavinking : I assume this is OK for you also ?

**Comment by gavinking** [comment]
This is working great now!
