### ISSUE TITLE
parameter names arg0, arg1, arg2 etc in Variables view

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1284]
When I step into the initialized of `HashMap` from `ceylon.collection` (loaded from my local repo), I see the initializer parameter names as `arg0`, `arg1`, `arg2` in the debugger Variables view.

**Comment by davidfestal** [comment]
It's related to the fact that the command line Ceylon compiler seems to compile *without* the `javac` 
`-g:vars` option.

In the backend compiler calls made by the IDE Ceylon incremental builder, we explicitly add the
`-g:lines,vars,source` option when calling `compiler.getTask()`.

It seems to me that, in order to provide a correct Ceylon debugging experience, we should also enable the `vars` debugging option, because of course we rely on internal variable names to match with the corresponding Ceylon declarations.

And of course, if it is not the default option for the compiler, then Herd will contain many Ceylon archives without the required debugging information, which will nearly prevent debugging inside project dependencies.
 
@FroMage, @quintesse, @tombentley , wdyt about that ?

**Comment by quintesse** [comment]
I thought that we already added debugging options by default, but after looking around in the code I see we actually only do this in our compiler test suite (see for example `ReportingTests` line 17 , `CeylonModuleRunner` line 213 and `CompilerTests` line 137).

After talking it over with @davidfestal I think it's advisable for Ceylon to always have debugging information available because the debugging experience without it is worse than Java's.

I *do* think we should still allow people to override this, for example if they pass `--jacac=-g:none` we should let that override our settings.

The idea I have now would be to do this in the Java option parsing part so this would affect all the currently know ways of calling the compiler. And add something like: "if no -g option was passed we add -g ourselves". (I'm not sure if we should simply use `-g` or a combination of specific flags liek suggested by David: `-g:lines,vars,source`)

**Comment by davidfestal** [comment]
Here is what the Javac doc says :
```
-g
    Generate all debugging information, including local variables. By default, only line number and source file information is generated.
-g:none
    Do not generate any debugging information.
-g:{keyword list}
    Generate only some kinds of debugging information, specified by a comma separated list of keywords. Valid keywords are:
    source
        Source file debugging information
    lines
        Line number debugging information
    vars
        Local variable debugging information
```
So I assume that adding -g would be sufficient.

**Comment by quintesse** [comment]
Ok, thanks! So do I understand correctly that in Java if you don't supply a `-g` option it is basically the same as doing `-g:lines,source` ?

**Comment by davidfestal** [comment]
yes, and it is confirmed by the fact that the classes produced by the current CLI only have source name and lines but not vars

**Comment by quintesse** [comment]
Ok @davidfestal , so we already found that `lines` and `source` are already always enabled by default in `javac` so I just did the same for `vars`. The `-g` option has no effect now (because it's now the default) but people can still override with `-g:XXX` if they want to.

**Comment by davidfestal** [comment]
Fixed after a rebuild of the SDK.

Thanks @quintesse !

**Comment by gavinking** [comment]
Thanks @davidfestal and @quintesse  :-)
