### ISSUE TITLE
Two Integer classes in Open Declaration

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1350]
Oh great, now I have as many as _three_ different `Integer`s for version 1.1.1 of the language module in Open Declaration. I have two from the IDE system repo alone, one of which is marked `native`, and one of which is not. So surely it's something to do with the new `native` stuff.

**Comment by davidfestal** [comment]
In fact it has not really something to do with the new native stuff. It only makes some behavior more clear.

It has to do with the fact that you probably have both java-only *and* javascript-enabled projects opened in your workspace. So the workspace contains at the same time 1 source version of the language module, and 1 binary version of the language module.

Until now, declarations coming from these 2 modules were considered equal. But now, declarations coming from the binary module are *not* seen as native (because they don't have the annotation), while declarations coming from the source module *do have* have the native annotation (with no backend). Since the native backend value is not the same (null != ""), then the declarations are considered different, and are both added, so that you find 2 occurrences of the same declaration in the search results.
However, before, we already didn't use to control whether the binary or the source version of a language module declaration would be returned in the search results, which was not a stable behavior.

So I think the fix is to decide that, when a binary declaration is found, we always return the corresponding source declaration if it exists.

**Comment by gavinking** [comment]
Thankyou!
