### ISSUE TITLE
initial build of project that depends on ceylon-sdk involves binary generation for ceylon-sdk

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1386]
@davidfestal is this normal: I have a project `hello` that depends on `ceylon-sdk`. At startup, while `Building hell`, I see that binary generation for `ceylon-sdk` is called. It doesn't seem right to me.

**Comment by davidfestal** [comment]
@gavinking : is it systematic ?

**Comment by davidfestal** [comment]
@gavinking : At startup it can be, sometimes, that the workspace detects some inconsistencies in the delta state saved during the previous version, and in this case it decides starts a true build at start.
Or more precisely, in this case the "initial build of project xxx" (that normally only build 1 project *without* the binary" will be propoted by the build manager to a *full* build of all the projects (which will lead to binary generation in all the projects).

The conditions in which this happens are not very clear, but this is something decided by the platform.

Hence the question : does it happen on *every* startup ?

**Comment by gavinking** [comment]
Not sure, but I don't *think* so.

On Fri, Jul 3, 2015 at 7:35 PM, David Festal <notifications@github.com>
wrote:

> @gavinking <https://github.com/gavinking> : At startup it can be,
> sometimes, that the workspace detects some inconsistencies in the delta
> state saved during the previous version, and in this case it decides starts
> a true build at start.
> Or more precisely, in this case the "initial build of project xxx" (that
> normally only build 1 project *without* the binary" will be propoted by
> the build manager to a *full* build of all the projects (which will lead
> to binary generation in all the projects).
>
> The conditions in which this happens are not very clear, but this is
> something decided by the platform.
>
> Hence the question : does it happen on *every* startup ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-ide-eclipse/issues/1386#issuecomment-118398136>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org

**Comment by davidfestal** [comment]
@gavinking : I've just checked and it still works.

But if your eclipse crashes or stops brutally, then you will have a full build (with binary generation)  triggered at start because in this case the workspace tree delta is invalidated by the platform.
Also, if you've had external changes to any binary archive, or things like that, then
any initial build action might be promoted to a full build of the workspace by the platform.

However in the case you only changed 1 file, only 1 file will have its binaries regenerated.
And in the case you didn't change anything, and the workspace was correctly saved at the end of the last session, then it will only full-typecheck the model of all projects but won't try to binary-generate anything.
It will just typecheck to load the Ceylon Modelof the source files in memory.

So can we close the issue ?

**Comment by gavinking** [comment]
I guess.
