### ISSUE TITLE
Find References broken in ceylon-ide-common project

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1420]
Whenever I try to run Find References on a method in the `ceylon-ide-common` project, I get zero results. I do not experience this behavior in any other Ceylon project.

@davidfestal would you take a look please

**Comment by davidfestal** [comment]
I don't get this behavior : if I search for references to `com.redhat.ceylon.ide.common.model.delta.DeltaBuilderFactory.buildDeltas()`, I get the expected references : 
- in `deltaBuilder.ceylon` itself (within the documentation)
- in `testUtils.ceylon`
- and even in the `com.redhat.ceylon.eclipse.ui` project, inside the `com.redhat.ceylon.eclipse.core.model.ProjectSourceFile.buildDeltaAgainstModel()` Java fonction.

Maybe you could give me some more details, so that I can reproduce it ?

**Comment by gavinking** [comment]
@davidfestal the only result I get is in `testUtils.ceylon`. The other results don't show up.

**Comment by gavinking** [comment]
OMG I'm _such_ a retard (oops: _wrongthinky microaggression!_) I had filtering set up.

Sorry for wasting your time @davidfestal!
