### ISSUE TITLE
renaming member of object expression broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1448]
Given:

```ceylon
shared {[Element+]*} permutations<Element>
        (List<Element> list) 
        => object satisfies {[Element+]*} {
    
    iterator()
            => object satisfies Iterator<[Element+]> {
        
        variable value counter = 0;
        
        shared actual [Element+]|Finished next() {
            print(counter);
            return finished;
        }
    };
};
```

If I rename `counter`, the declaration itself is not renamed.

**Comment by gavinking** [comment]
Actually this is just a special case of the bigger bug mentioned in #1460. So I'm closing this dupe issue.

**Comment by davidfestal** [comment]
was not fixed by the fix of #1460.

**Comment by davidfestal** [comment]
After some debugging, it appears that it is a side-effect of the following commit : e105b36

Since we fully skip the children of the object expression defined with the `SpecifierStatement`, we don't even visit the declaration of `counter`.

@gavinking : since I don't know your reasoning behind the involved commit, I'm not sure of the best way to fix this.

**Comment by davidfestal** [comment]
So I'll unassign myself from this issue

**Comment by gavinking** [comment]
Ah, OK, thanks.

**Comment by gavinking** [comment]
I have reopened #1020 and I'm closing this one.

**Comment by gavinking** [comment]
Confirmed fixed.
