### ISSUE TITLE
lots of new bugs in Rename refactoring

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1460]
OK, so Rename is now a big mess. (Not really anybody's fault, since there were no tests, of course.)

Things I've noticed:

1. In `x.member`, placing the caret right between `x` and `.` and hitting ⌘⌥R selects `member` for renaming instead of `x`. (This may be due to the changes to `FindNodeVisitor`.)
2. Very often, selecting a usage of a local variable, and hitting ⌘⌥R selects the usage for renaming, but does not select the actual definition.

This needs to go through a full retest / bugfix process.

**Comment by davidfestal** [comment]
I'll have a look to that today

**Comment by gavinking** [comment]
Thanks.

**Comment by davidfestal** [comment]
@gavinking : Now that `nodes` and `FindNodeVisitor`, etc ... are in common, let me add tests for those. This will help finding out the underlying bugs that produced these regressions. So it will also be easier for you to give your thought about the expected result of specific use cases.

**Comment by bjansen** [comment]
Additional problem: in `value \imodule = ...`, placing the caret in `\imodule` and hitting ⌘⌥R selects `\imodu`.

**Comment by gavinking** [comment]
Note: we need to check that the fix for this also fixes #1448.

**Comment by davidfestal** [comment]
Fixed by ceylon/ceylon-ide-common@0d0a755

However the `\imodule` case is not fixed. This is another problem for which I've just created issue #1471.

Also #1448 is finally *not* fixed by this. This seems to be a different (at least partly different) problem. So I'll reopen it.

@gavinking : apart from these 2 cases, can you confirm everything else is fixed also on your side ?

**Comment by gavinking** [comment]
For now it looks much better to me. If I notice anything else, I will open a separate issue.

Thanks!
