### ISSUE TITLE
Breakpoints in Java applications stop in .class instead of .ceylon

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1465]
When debugging a Java application that contains Ceylon code (for example ceylon-ide-eclipse), if I put a breakpoint in a Ceylon file, the debugger will stop and then step over/into/etc in the corresponding `.class file`:

![image](https://cloud.githubusercontent.com/assets/281528/9712477/24d685ca-554b-11e5-9348-185ab4053faf.png)

This causes several (minor) problems:
- the file is not correctly highlighted
- I can't add other breakpoints unless I go back to the `.ceylon` file
- navigation (ctrl-click) doesn't work

**Comment by davidfestal** [comment]
@gavinking , @bjansen :

I did this now (in priority) since that will make the IDE-related development  & debugging (for Eclipse *and* IntelliJ) *much easier*.

Let me explain the changes.

For the following types of `Debug Configuration`, I added an _alternate_ __*Ceylon-aware*__ launcher that we can use instead of the default one, in order to have the debugger correctly open the Ceylon Editor for class files generated from Ceylon code :
- **JavaApplication**
- **Java Remote Application**
- **Eclipse Application**
- **JUnit**
- **JUnit Plug-in Test**
- **SWTBot Test**

For the launch configuration types, when creating / using a `Debug` launch configuration, you will have to specify the launcher you want to use. In order to avoid setting it each time you create / use the launch configurations, you can setup defaults in the following standard Eclipse preference page : `Run/Debug -> Launching -> Default Launchers`.

For the moment, I haven't added the Ceylon-specific debugging support to these alternate launchers, but this change should make easy to add parts of the Ceylon debugging support to such debugging sessions in the future.

**Comment by davidfestal** [comment]
And FTR it was a pleasure to use Ceylon mixins to apply the same transverse feature to all these existing launchers. See : 
https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/source/com/redhat/ceylon/eclipse/core/launch/CeylonAwareLaunchConfiguration.ceylon
and
https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/source/com/redhat/ceylon/eclipse/core/launch/CeylonAwareSourceLookupDirector.ceylon

**Comment by gavinking** [comment]
OK, so that's nice, but how is an _actual user_ supposed to find this feature? :-)

**Comment by davidfestal** [comment]
When you create a new launch configuration of one of these types, if you don't have *previously* setup default launchers yourself in the workspace preferences, you will have to *explicitly* select the launcher you want to use. So the user *will* see the feature normally (unless he already has alternate launcher for these configuration types with already selected default, which is not very probable).

**Comment by gavinking** [comment]
OK.

On Wed, Sep 23, 2015 at 5:08 PM, David Festal <notifications@github.com>
wrote:

> When you create a new launch configuration of one of these types, if you
> don't have *previously* setup default launchers yourself in the workspace
> preferences, you will have to *explicitly* select the launcher you want
> to use. So the user *will* see the feature normally (unless he already
> has alternate launcher for these configuration types with already selected
> default, which is not very probable).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceylon/ceylon-ide-eclipse/issues/1465#issuecomment-142633500>
> .
>



-- 
Gavin King
gavin@ceylon-lang.org
http://profiles.google.com/gavin.king
http://ceylon-lang.org
http://hibernate.org
http://seamframework.org
