### ISSUE TITLE
Ceylon IDE doesn't compile

### ISSUE THREAD

**Issue by jpragey** [ceylon/ceylon-ide-eclipse#1484]
Seems that plugin compilation failed for a while:
https://vietj.ci.cloudbees.com/job/ceylon-daily/
Is there any recent change on compilation process ?

**Comment by davidfestal** [comment]
Not in the last week afair. I'll have a look more deeply. Thanks for the report !

**Comment by davidfestal** [comment]
Until now, specifying a dummy version in a `<add>` directive of the `overrides.xml` was accepted if a corresponding `<set>` override was also present inside the file, since the `<set>` is intended to override the version number of all the modules version that have this name.

However, such a case of a dummy version overridden by a `<set>` override, is not explicitly specified and tested. Indeed it seems there is a possibility that, in some cases, this might fail for dependencies added through `<add>` override, maybe according to the order in which the `overrides.xml` rules are processed. So it might have been working by accident until now, and now something unrelated changed in the overall configuration and it doesn't work anymore.

I think that for the moment I'll simply fix all the versions to the right version when generating the `overrides.xml` file through the `ant` build.
