### ISSUE TITLE
Allow attaching Java sources from a folder instead of an archive

### ISSUE THREAD

**Issue by bjansen** [ceylon/ceylon-ide-eclipse#1491]
I would like to be able to attach sources from an exploded directory instead of a `.src` archive. It would be useful when we import Java modules for which we don't have sources in a single archive. 

For example, IntelliJ dependencies consist of multiple JARs for which there's no source archive, only a git repository. Currently, I'm unable to have proper documentation or "go to declaration" when I use the IntelliJ API from Ceylon.

**Comment by davidfestal** [comment]
@gavinking , @bjansen :

So let me tell some more about that issue : 

- I've made it a high-priority issue, and fixed it because it will be a great help in the IDE development (common,eclipse, intelliJ).

- In the `.ceylon/ide-config` , in the `project` section, we have a new option named `source-attachments` : it defines the path (relative to the project location) of a properties file we use to define source attachments. If this option is not present, the default source attachment properties file will be the `attachments.properties` at the root of the project.

- The source attachments are only for Java archives.  `Car` archives are expected to have their corresponding source archive inside the Ceylon repositories. 

- The source attachment properties file consists of a list of rules that have the following form : 
```
<moduleName or '*'>/<moduleVersion or '*'>/path=<path to the source attachment archive or folder>
```
For example : 
```
com.redhat.ceylon.common/*/path=../../../ceylon-common/src
com.redhat.ceylon.compiler.java/*/path=../../../ceylon-compiler
com.redhat.ceylon.compiler.js/*/path=../../../ceylon-js
com.redhat.ceylon.module-resolver/*/path=../../../ceylon-module-resolver
com.redhat.ceylon.typechecker/*/path=../../../ceylon-spec
ceylon.runtime/*/path=../../../ceylon-runtime
com.redhat.ceylon.dist/*/path=../../../ceylon-dist/osgi/src
```

- The path to the source attachment can be either _absolute_ or _relative_ : 
    - _if absolute,_ it can be either : 
        - the full path of a file or directory on disk, 
        - or (for Eclipse) the full path of a resource from the Eclipse workspace root.
    - _if relative,_ it can either : 
        - __start with `./` or `../`*__, in which case it is the path of a file or directory on disk, relative to the project location on disk, 
        - or (for Eclipse) be the relative path of a resource from the Eclipse project resource __if it doesn't start with  `./` or `../`__.

- When the source attachment path is a directory, it can be the parent (or ancestor) of any source directory in which source has to be searched. Eclipse will search for the right source directories under this source path automatically.

- In order to _take in account new or modified source attachments_ in the properties file, I added a new command in the `Ceylon Explorer` contextual menu of a Ceylon project : `Reset Source Attachments`. This will resolve the project classpath again, taking in account the new source attachment rules.

- Finally I've just pushed the source attachments file for the Eclipse plugin. So now the source code for all the sibling project is correctly attached : typechecker (even the generated code), compiler (even the Javac code),  CMR, Ceylon OSGI activator, etc ... It will also allow attaching source code for external archives (such antlr, etc ...) in order to also get the JavaDoc when using them in the Ceylon code.

- Enjoy !

**Comment by gavinking** [comment]
> - In order to _take in account new or modified source attachments_ in the properties file, I added a new command in the `Ceylon Explorer` contextual menu of a Ceylon project : `Reset Source Attachments`. This will resolve the project classpath again, taking in account the new source attachment rules.

That doesn't sound quite right: can't it just watch for changes to the `.properties` file via the resources API?

**Comment by davidfestal** [comment]
@gavinking : I agree that a change to the properties file could be detected automatically.
However, the `Reset Resource Attachments` has a broader use than reloading the properties file. More precisely, this action also allows reloading source archives of CAR or Maven archives (in case the source were added on the disk) without having to restart Eclipse.
