### ISSUE TITLE
ceylon tests often don't seem to show up in the Ceylon Test view

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1495]
There seems to be a problem where you can run tests but the results don't show up in the view.

**Comment by lukedegruchy** [comment]
I've tried running several tests, both by right clicking the package or Ceylon file in Ceylon Explorer and right-clicking within the editor Window and I don't see anything in the Ceylon Test View.

**Comment by quintesse** [comment]
Ok, so this is how I can reproduce this behaviour without fail:

 - make sure you don't have any "Ceylon Test" tab open on your workspace
 - exit and restart Eclipse
 - right click on any Ceylon module containing tests and select "Ceylon Test"

What happens then is:

 - A "Ceylon Test" tab will open
 - Tests will run but no output will appear

Even stranger is that when I try to rerun the test by right clicking again suddenly the menu is much shorter and all items are grayed out!

If I now close the tab again the menu goes back to normal I can rerun the test resulting in the same behaviour as above.

**But...** very important, if I don't close the tab but select another tab, any tab, so it becomes the active tab instead of the "Ceylon Test" the menu also goes back to normal and I can run the tests again **but his time the tests actually show up!**

Also if you don't close the tab and exit and restart Eclipse everything works just fine the first time you run the tests.

So I'm guessing this is some kind of initialization problem in the code for the "Ceylon Test" tab, the tests get run but the results just never get displayed because something somewhere is configured right until the tab loses focus.

**Comment by quintesse** [comment]
Ah, another way to make it work:

 - Run the tests
 - "Ceylon Tab" shows up but doesn't display anything
 - Click inside the "Ceylon Tab"
 - Menu goes back to normal
 - Rerun the tests
 - Tests no show up correctly

**Comment by FroMage** [comment]
@thradec any idea?

**Comment by thradec** [comment]
Should be done, if you will see something strange, please report.

**Comment by FroMage** [comment]
Thanks!

**Comment by gavinking** [comment]
Thankyou @thradec!
