### ISSUE TITLE
Incremental compilation of SDK includes unchanged modules

### ISSUE THREAD

**Issue by ASzc** [ceylon/ceylon-ide-eclipse#1505]
I'm using `Eclipse Mars 4.5.0` with `Ceylon IDE 1.1.1.v20150721-1337-Final`.

When I save any change (even just a whitespace change) to a [ceylon.net.http.client](https://github.com/ASzc/ceylon-sdk/tree/http-rewrite/source/ceylon/net/http/client) source file in the SDK project, and then save it, a long (>10 seconds) compilation step follows. This appears in the Progress tab, and will block subsequent save operations until it completes.

I would expect that a few files in the current module might need to be recompiled, but it seems that files in unrelated modules (such as ceylon.collection) are being recompiled as well.

I've tried to get a succinct log of this activity, but the best I have been able to find is the "code" log level for the compiler. Since GitHub won't let me attach the file, I have put it temporarily [here](http://szc.ca/ceylon-ide-log_code_2015-09-27.txt.gz).

**Comment by gavinking** [comment]
@davidfestal it's possible that there is something very broken with incremental compilation right now. _Changing whitespace_ in a toplevel class in one unit, that is not used _anywhere_ seems to result in compilation of other toplevel declarations in the same module.

That can't be right. Could you take a look please?

**Comment by davidfestal** [comment]
@gavinking : yes, I'll have a look as soon as I've pushed to a branch my current changes that I need to leave in a consistent state.

**Comment by gavinking** [comment]
Thanks.

**Comment by davidfestal** [comment]
@gavinking : this might be related to car archives being not fully generated because of some error in the code encountered by the compiler backend. Inside the IDE we keep track of all binary files that should have been generated by the backend inside the Car archives, but have *not*.
And we include all the related source files in the next incremental build. This is a strong requirement for the consistency of next incremental builds and the overall Ceylon model (that is loaded from binaries).

To see if this extraneous files included in the incremental build come from this reason, please keep a look regularly at the "Infos" problem markers when you are about to save a file that has errors. Then you will see if some classes were missing from the current CAR archives generated by the previous build. If it is the case, then it is a normal behavior to rebuild the source files corresponding to those missing binary class files.

All this is related to the fact that error recovery in the compiler Java backend is in bast-effort mode, but doesn't work fully in all the scenarios.

**Comment by gavinking** [comment]
@davidfestal I don't see how that can possibly be the explanation. I don't have any failed compilation markers or other errors.

Look, just turn on "code" logging and you will see all the unnecessary activity.

**Comment by davidfestal** [comment]
- First point : As shown by the above commit, there was a case when the `duplicateDeclarations` list of a unit was filled though no error was there. The `JavaList` class of the `ceylon.iterop.java` module was in this case (related to refinement of Java overloaded methods).
Since units with duplicate declarations are always added in an incremental build, the `JavaList` was added to the incremental build, even when only adding a space in the `ceylon.net.http.client::Request` file.
This case has been fixed.

- Second point : Until now, the Javascript backend *always* generates Javascript for all the source files (Javascript incremental build isn't setup for the moment). This is a know limitation. But of course, if the Javascript backend is enabled this adds much log when the `code` logging is enabled.

- Third point : even when a file is modified with no structural changes, the transitively-depending source files still have to be typechecked. For now the incremental build filtering based on the AST deltas only reduces the files for which binary generation is called. This is a limitation due to how the ceylon model is managed.

So currently when I modify the `ceylon.net.http.client::Request` file with only the JVM backend enabled, I can see from the progress windows *and* the `code` logging, that 8 files (all from the `ceylon.net` module) are typechecked again (because they depend on `Request`) and *only* the `Request.ceylon` file is included in the JVM backend binary generation phase. 

This seems correct to me.

@ASzc , @gavinking : if you find specific files that bring the compilation of abnormal dependencies (taking in account the 3 cases mentioned earlier), please could you give me the exact name of the file, the enabled backends on your SDK project, as well as the console output of your `code` logging related to the incremental build (please clear the console just before) ?

**Comment by gavinking** [comment]
@davidfestal OK, so here's some observations:

1. The behavior I noticed before seems to have been fixed. When only the Java backend is enabled, I no longer see unrelated files being compiled, AFAICT.
2. JavaScript incremental build should be something very easy to do, since it is module-level. Right now changing anything in any file results in all SDK project modules being rebuilt, but it should be pretty easy to only rebuild the affected _modules_. OTOH, the JS backend is so fast compared to the typechecker and the Java backend that this doesn't seem to be a really major problem problem right now.
3. Help me understand your third point. Why precisely do we have to typecheck things we already know we don't have to recompile? (I think I can guess the answer but tell me anyway.)

FTR after playing around, it seems to me that this bug is now fixed and we can close it.

**Comment by davidfestal** [comment]
@gavinking : in the Ceylon model, declaration dependencies are modeled with direct references between model objects (`Declaration` and `Type` objects mainly). When we incrementally typecheck a unit, the declarations in the previous unit are replaced in the related package by the declarations of the new unit. But the depending units, if not typechecked again also, will keep references to the declarations of the old unit. This brings strong inconsistencies in the model.

**Comment by gavinking** [comment]
What I figured you would say.

**Comment by davidfestal** [comment]
so do you think we can close this issue now ?

**Comment by davidfestal** [comment]
Let me close this. @ASzc : please reopen this issue if you still encounter problems that cannot be explained by the 3 cases explained above (https://github.com/ceylon/ceylon-ide-eclipse/issues/1505#issuecomment-147202552).

**Comment by ASzc** [comment]
Regarding:

1. I'm unsure how I can get an IDE build with this fix in it. I'm using the Development update site, but I don't see anything new there.
2. ceylon.net is Java only, so disabling the JS backend is acceptable. I got maybe a marginal 
improvement, hard to tell.
3. That's not going to be a big factor for editing ceylon.net I think (no incoming dependencies at all)?

Further to point 1: Do errors force a rebuild? I often find there are hundreds of standing errors in SDK code I'm not working on, but I can't remember them causing this issue previously.

**Comment by ASzc** [comment]
I updated to `Ceylon IDE 1.2.0.v20151020-1903-Final` today, this cleared up all of the standing SDK errors, and I now see an appropriate number of things being recompiled.

**Comment by davidfestal** [comment]
cool. good news

**Comment by ASzc** [comment]
This reappeared again after I updated to 1.2.1 soon after 1.2.0. I think the reason it worked with the 1.2.0 version was the SDK modules at version 1.2.0 were available outside the project, thus no need to recompile.

It doesn't look like this is easily fixable. One thing that would make this more tolerable is if a new user operation (saving, adding a package, etc.) cancelled the currently running build, instead of a modal progress box popping up and forcing me to wait for several minutes before doing anything else.

Currently I'm in the pattern of putting off saving for as long as possible, then doing something else while it compiles everything again. This isn't great because of the mental context switching, it makes working on the SDK more of a pain than it should be.
