### ISSUE TITLE
hover on true.string shows Javadoc for java.lang.Object.string

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1553]
Hover over `true.string`, and you'll see.

**Comment by bjansen** [comment]
The hover is showing the Javadoc because of [this condition](https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/code/hover/DocumentationHover.java#L1735):

```
        Node rn = getReferencedNode(dec);
        if (rn instanceof Tree.Declaration) {
```
The code is looking for a `doc` or an anonymous annotation on a `Tree.Declaration`. In our case, we have a `Tree.SpecifierStatement` instead of a `Tree.Declaration`, so it delegates to `appendJavadoc()`.

The following code seems to fix this issue, however I'm not sure it's valid for any `SpecifierStatement`:

```
        Node rn = getReferencedNode(dec);
        if (rn instanceof Tree.SpecifierStatement) {
            rn = getReferencedNode(((Tree.SpecifierStatement) rn).getDeclaration().getRefinedDeclaration());
        }
        if (rn instanceof Tree.Declaration) {
...
```

@gavinking wdyt?

**Comment by gavinking** [comment]
@bjansen Your fix looks pretty reasonable to me.

**Comment by gavinking** [comment]
Thanks @bjansen. I made a tiny adjustment.
