### ISSUE TITLE
F2 is broken

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1600]
F2 is supposed to pop up the regular documentation hover, by on master it is activating the *expression* hover. (This bug is not happening in 1.2.0.)

@bjansen surely a side-effect of the abstraction work.

**Comment by bjansen** [comment]
Yeah about that, I thought I found a bug in DocumentationHover, and fixed it in the Ceylon version. This issue is a side-effect of my fix.

Take a look at this code: https://github.com/ceylon/ceylon-ide-eclipse/blob/master/plugins/com.redhat.ceylon.eclipse.ui/src/com/redhat/ceylon/eclipse/code/hover/DocumentationHover.java#L359-L360

I think the correct reasoning should be: if the selected text is located inside the hovered region, then show the doc. I inverted the logic because hovering `"abcd"`, while `b` was selected wasn't showing the documentation for character `b`, it only worked if the string and the selection were both `b`. That didn't work because the condition was checking if the hover was inside the selection.

Which one do you think is the correct solution?

```
                if (offset<=hoffset && 
                    offset+length>=hoffset+hlength) {
```
or
```
                if (offset>=hoffset && 
                    offset+length<=hoffset+hlength) {
```

**Comment by gavinking** [comment]
Well as far as I can tell, the current behavior is exactly backwards.

**Comment by gavinking** [comment]
What that code is supposed to be saying is: if the hovered node is *inside* the selection, display the hover for the selected expression. Right now it says the opposite.

**Comment by gavinking** [comment]
Fixed.

**Comment by bjansen** [comment]
Yeah I know it's backwards, because I made it that way. Fix your fix, if you select a single character in a multi-char string, and hover that character, it won't display this character's information. It only works if the string contains a single char. That's why I inverted the condition.

**Comment by gavinking** [comment]
> With your fix, if you select a single character in a multi-char string, and hover that character, it won't display this character's information. It only works if the string contains a single char. 

@bjansen well the cause of that is `SourceInfoHover.getHoverRegion()` which I copied from the JDT version that selects the current word. I could change it back to just `return new Region(offset,0)`.
