### ISSUE TITLE
hovering over 1.0.integer does not show thrown exception type

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1633]
When I hover over `integer` in `1.0.integer` I don't see the content of the `throws` annotation.

**Comment by gavinking** [comment]
@bjansen does this also affect the IntelliJ plugin?

**Comment by bjansen** [comment]
This expressions is not valid:

> method or attribute is not visible: 'float' of type 'Float'

and `float` navigates to the parameter of `Float`, so I don't know where it should find a `throws`.

FTR I'm using `value a = 1.0.float`

**Comment by gavinking** [comment]
@bjansen WDYM, it says `1.0.integer`. *Whistles a happy tune...*

**Comment by bjansen** [comment]
I can see the throws part in IntelliJ.

**Comment by bjansen** [comment]
This happens because the [following condition](https://github.com/ceylon/ceylon-ide-common/blob/master/source/com/redhat/ceylon/ide/common/doc/DocGenerator.ceylon#L1026) is not true:

```ceylon
if (is Tree.MetaLiteral typeArgTerm,
    exists dec = typeArgTerm.declaration) {
```

`typeArgTerm` is the class literal between backticks in `Float.ceylon`:

```ceylon
throws (`class OverflowException`,
```

The interesting part is that while `typeArgTerm.declaration` is null, `typeArgTerm.type.declaration` is not, which means the model is loaded.

In IntelliJ, I can see that `typeArgTerm.declaration` is set by `ExpressionVisitor`, which is called by `PhasedUnit.analyseTypes()` (which is invoked on each phased unit of each dependency). If I set the same breakpoint in Eclipse, this part of `ExpressionVisitor` is never called. I suspect this is because `CeylonBuilder` does not call `analyseTypes()` on `ceylon.language`.

@davidfestal I'm stuck on this one, could you please take a look?

**Comment by davidfestal** [comment]
@gavinking , @bjansen: The reason is really simple in fact: the Java implementation of the method (in the `runtime` source directory of the `ceylon.language` project) doesn't have the `throws` annotation while the Ceylon source header declaration has it.
The `throws` annotation should be added to the Java source IMO.
@FroMage , @quintesse , @tombentley : wdyt ?

**Comment by davidfestal** [comment]
@gavinking , @bjansen, @FroMage , @quintesse , @tombentley : any thoughts ?

**Comment by tombentley** [comment]
We can't add the annotation because the compiler doesn't support Java
depending on Ceylon like that.

**Comment by davidfestal** [comment]
@tombentley : so I assume that, in the model loader we should have a look to the native header in order to retrieve such annotations and add them to the native implementation Declaration  ?
