### ISSUE TITLE
Add support for the `ceylon bootstrap` command

### ISSUE THREAD

**Issue by davidfestal** [ceylon/ceylon-ide-eclipse#1725]
Provide:
- an Option  in the `New Ceylon Project` wizard
- a Project contextual menu item
that call the new `ceylon bootstrap` command to create the `ceylonb` boostrap scripts at the root of the Ceylon project.

**Comment by quintesse** [comment]
You didn't actually test it, did you? ;)

It doesn't work. I forgot to mention that the `lib/ceylon-bootstrap.jar` isn't actually the same as the `repo/ceylon/bootstrap/x.y.z/ceylon-bootstrap-x.y.z.jar` ! The lib version is smaller and more stripped down. So I'm afraid we'll still have to include it in the `embeddedRepository`.

And even then it won't work because we need to say which versions the bootstrap needs to install. By default it will use the current version... but of course **our** current version , the code we use from "master", hasn't been released yet so can't be downloaded by the user.

So we better hard-code the last release version... but we'll have to remember to update that.

Another nice option would be to have a dropdown next to the "Create Ceylon Bootstrap files" showing the versions "1.2.2", "1.2.1", "1.2.0", "1.1.0" and "1.0.0".

**Comment by davidfestal** [comment]
I tested the generation of the `ceylonb` command sure. But what you mean is that I didn't test the execution of the resulting `ceylonb` script right ?

**Comment by quintesse** [comment]
Yeah :)

**Comment by davidfestal** [comment]
But I don't get it in the `lib` version. I get it in the embedded repo, at `ceylon/bootstrap/<version>/bootstrap-<version>.jar`

**Comment by quintesse** [comment]
like I explained, that's not the correct version, you need the lib one

**Comment by davidfestal** [comment]
so you need "smaller and more stripped down" version. The bigger doesn't work? OK

**Comment by davidfestal** [comment]
It's a pity that I didn't know that when adding this in release 1.2.2 :-)

**Comment by quintesse** [comment]
A pity we didn't test it when adding it in the 1.2.2 release :-p

Luckily you can easily update the IDE

**Comment by davidfestal** [comment]
yeah

**Comment by quintesse** [comment]
But we can't wait too long with fixing this. Anyone making new projects with this Eclipse version will be creating broken bootstraps :(

**Comment by davidfestal** [comment]
I'll do it tomorrow

**Comment by quintesse** [comment]
Sure, not now obviously ;)
