### ISSUE TITLE
Support relative path for aether repository

### ISSUE THREAD

**Issue by DiegoCoronel** [ceylon/ceylon-ide-eclipse#1761]
This is a new feature in backend, it would be good to have support in eclipse.
https://github.com/ceylon/ceylon/issues/6142

**Comment by quintesse** [comment]
Btw, possibly within the IDE the relative path would be taken relative the the Eclipse startup folder instead of the project folder (you might have different projects open after all). If that's the case I imagine the IDE would have to convert the relative path to an absolute path when passing it to the compiler etc. If so care has to be taken that that absolute path doesn't end up in the config file, for the CLI tools the path must remain relative of course.

**Comment by DiegoCoronel** [comment]
This issue for me is a blocker, because my team contains 10 devs and I really want to start coding in ceylon, but i need to make a smooth transition, so this is something my team will complain if i try right now

**Comment by davidfestal** [comment]
It already worked when I tried, it seems the real blocker was #1764 that is now fixed. @DiegoCoronel : do you confirm?

**Comment by DiegoCoronel** [comment]
@davidfestal confirmed, perfect !! Thanks :)
