### ISSUE TITLE
Ceylon classpath containers should be exported by default

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-ide-eclipse#1777]
If a Java project depends on a Ceylon project, it needs the classpath containers to be exported. There's _no way_ that any user is ever going to realize that, so they should be exported by default.

**Comment by davidfestal** [comment]
I would prefer a clean error with a quick fix.

**Comment by gavinking** [comment]
I'm not sure why.

**Comment by gavinking** [comment]
I think things should Just Work by default.

**Comment by davidfestal** [comment]
as much as possible yes :-)

**Comment by davidfestal** [comment]
This may have impact on the model loader in case some other Ceylon project depends on the Ceylon project with exported entries. some times ago it would surely have introduced problems, but now I think it's not a problem anymore due to the model loader being much more robust when choosing the classpath entries in which it searches for declarations. However I'll check still.
