### ISSUE TITLE
add --javac compile option

### ISSUE THREAD

**Issue by LisiLisenok** [ceylon/ceylon-ide-eclipse#1787]

**Comment by davidfestal** [comment]
This is now working through the `.ceylon/ide-config` file.

Just create such an `ide-config` text file besides the well-known `.ceylon/config` file, with the following content:

```
[project]
javac=<your javac option>
```

For example:

```
[project]
javac=-source=1.3
```

You can add as many as `javac=` lines as you need, knowing that each `javac=` line contains only one javac option.

Does it fit your need @LisiLisenok ?

**Comment by LisiLisenok** [comment]
@davidfestal yes, thank you, this is nice.

**Comment by bjansen** [comment]
@LisiLisenok in Ceylon 1.2.3 Eclipse will look for javac options in the new and official location in `.ceylon/config` instead of `.ceylon/ide-config`. These options will now be accepted by the CLI too.

* if you don't specify any `target` option, the build will use the current JDK version (`-target=8` for JDK 8 etc)
* you can force your own target using:
```
    [compiler "jvm"]
    target=8
```
* or any other javac option using:
```
    [compiler "jvm"]
    javac=-target=8
    javac=-Xmx5T
```

You'll have to modify your project config once you start using Ceylon 1.3.1 (snapshot or final version), sorry for this.

**Comment by bjansen** [comment]
Sorry, Ceylon 1.3.1, not 1.2.3 :D

**Comment by LisiLisenok** [comment]
@bjansen thank you very much! I am happy with the option :)
