### ISSUE TITLE
completion stops working: "no proposals"

### ISSUE THREAD

**Issue by jvasileff** [ceylon/ceylon-ide-eclipse#1830]
Even after restarting Eclipse, completion attempts fail immediately with "no proposals".

This also happened shortly before release. I then installed a release candidate build of the plugin from a url provided by @davidfestal, and this fixed the issue. But, yesterday, it happened again, without any changes to my installation that I am aware of.

So, I fixed it again by upgrading the plugin again, this time to the actual release build from the public update site (20160916 instead of 20160915).

But not understanding why it broke, I don't have a lot of confidence it won't break again.

A screenshot of the 20160915 plugin versions as well as a full Eclipse log is attached.

![screen shot 2016-09-22 at 10 11 02 am](https://cloud.githubusercontent.com/assets/236050/18751704/f810be7c-80ad-11e6-8d14-a7a9a88134fa.png)

[eclipse-log.txt](https://github.com/ceylon/ceylon-ide-eclipse/files/487509/eclipse-log.txt)

**Comment by bjansen** [comment]
The behavior changed just before the release. It used to show "no proposals" when the completion was cancelled because you continued typing or moved the caret using the arrows etc. Now it will simply cancel the completion without showing the popup.

Keep in mind that the first call to the completion system can take a little while, because it scans your dependencies and loads declarations in memory. That's why the released version will show a message in the status bar. 

In a few builds that were done just before the release, Eclipse would show no sign that it was loading those declarations (except the mouse pointer that changed to "busy", which can easily be missed), and after the next mouse/keyboard event it would immediately show "no proposals". I think that's what you were experiencing. If you waited patiently, once all the declarations were loaded, the actual results were showing up immediately in later calls though.

**Comment by jvasileff** [comment]
@bjansen I wouldn't rule out something specific to my environment, but that doesn't sound like the cause. The errant state persisted across multiple Eclipse relaunches, was present in different projects (even after closing all but a very simple project), after waiting, after "project clean" etc, and for multiple days. After upgrading the plugin, completion works great.

**Comment by bjansen** [comment]
@jvasileff do you still have this error? Can we close the issue?

**Comment by jvasileff** [comment]
ok
